/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuditRouteRouteImport } from './routes/audit/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditQueriesRouteRouteImport } from './routes/audit/queries/route'
import { Route as AuditPlansRouteRouteImport } from './routes/audit/plans/route'
import { Route as AuditCategoriesRouteRouteImport } from './routes/audit/categories/route'
import { Route as AuditQueriesIndexRouteImport } from './routes/audit/queries/index'
import { Route as AuditPlansIndexRouteImport } from './routes/audit/plans/index'
import { Route as AuditCategoriesIndexRouteImport } from './routes/audit/categories/index'
import { Route as AuditQueriesQueryIdRouteImport } from './routes/audit/queries/$queryId'
import { Route as AuditPlansPlanIdRouteImport } from './routes/audit/plans/$planId'
import { Route as AuditCategoriesCategoryIdRouteImport } from './routes/audit/categories/$categoryId'

const AuditRouteRoute = AuditRouteRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditQueriesRouteRoute = AuditQueriesRouteRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AuditRouteRoute,
} as any)
const AuditPlansRouteRoute = AuditPlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuditRouteRoute,
} as any)
const AuditCategoriesRouteRoute = AuditCategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuditRouteRoute,
} as any)
const AuditQueriesIndexRoute = AuditQueriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditQueriesRouteRoute,
} as any)
const AuditPlansIndexRoute = AuditPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditPlansRouteRoute,
} as any)
const AuditCategoriesIndexRoute = AuditCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditCategoriesRouteRoute,
} as any)
const AuditQueriesQueryIdRoute = AuditQueriesQueryIdRouteImport.update({
  id: '/$queryId',
  path: '/$queryId',
  getParentRoute: () => AuditQueriesRouteRoute,
} as any)
const AuditPlansPlanIdRoute = AuditPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AuditPlansRouteRoute,
} as any)
const AuditCategoriesCategoryIdRoute =
  AuditCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AuditCategoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteRouteWithChildren
  '/audit/categories': typeof AuditCategoriesRouteRouteWithChildren
  '/audit/plans': typeof AuditPlansRouteRouteWithChildren
  '/audit/queries': typeof AuditQueriesRouteRouteWithChildren
  '/audit/categories/$categoryId': typeof AuditCategoriesCategoryIdRoute
  '/audit/plans/$planId': typeof AuditPlansPlanIdRoute
  '/audit/queries/$queryId': typeof AuditQueriesQueryIdRoute
  '/audit/categories/': typeof AuditCategoriesIndexRoute
  '/audit/plans/': typeof AuditPlansIndexRoute
  '/audit/queries/': typeof AuditQueriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteRouteWithChildren
  '/audit/categories/$categoryId': typeof AuditCategoriesCategoryIdRoute
  '/audit/plans/$planId': typeof AuditPlansPlanIdRoute
  '/audit/queries/$queryId': typeof AuditQueriesQueryIdRoute
  '/audit/categories': typeof AuditCategoriesIndexRoute
  '/audit/plans': typeof AuditPlansIndexRoute
  '/audit/queries': typeof AuditQueriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteRouteWithChildren
  '/audit/categories': typeof AuditCategoriesRouteRouteWithChildren
  '/audit/plans': typeof AuditPlansRouteRouteWithChildren
  '/audit/queries': typeof AuditQueriesRouteRouteWithChildren
  '/audit/categories/$categoryId': typeof AuditCategoriesCategoryIdRoute
  '/audit/plans/$planId': typeof AuditPlansPlanIdRoute
  '/audit/queries/$queryId': typeof AuditQueriesQueryIdRoute
  '/audit/categories/': typeof AuditCategoriesIndexRoute
  '/audit/plans/': typeof AuditPlansIndexRoute
  '/audit/queries/': typeof AuditQueriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/audit/categories'
    | '/audit/plans'
    | '/audit/queries'
    | '/audit/categories/$categoryId'
    | '/audit/plans/$planId'
    | '/audit/queries/$queryId'
    | '/audit/categories/'
    | '/audit/plans/'
    | '/audit/queries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/audit/categories/$categoryId'
    | '/audit/plans/$planId'
    | '/audit/queries/$queryId'
    | '/audit/categories'
    | '/audit/plans'
    | '/audit/queries'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/audit/categories'
    | '/audit/plans'
    | '/audit/queries'
    | '/audit/categories/$categoryId'
    | '/audit/plans/$planId'
    | '/audit/queries/$queryId'
    | '/audit/categories/'
    | '/audit/plans/'
    | '/audit/queries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRouteRoute: typeof AuditRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/queries': {
      id: '/audit/queries'
      path: '/queries'
      fullPath: '/audit/queries'
      preLoaderRoute: typeof AuditQueriesRouteRouteImport
      parentRoute: typeof AuditRouteRoute
    }
    '/audit/plans': {
      id: '/audit/plans'
      path: '/plans'
      fullPath: '/audit/plans'
      preLoaderRoute: typeof AuditPlansRouteRouteImport
      parentRoute: typeof AuditRouteRoute
    }
    '/audit/categories': {
      id: '/audit/categories'
      path: '/categories'
      fullPath: '/audit/categories'
      preLoaderRoute: typeof AuditCategoriesRouteRouteImport
      parentRoute: typeof AuditRouteRoute
    }
    '/audit/queries/': {
      id: '/audit/queries/'
      path: '/'
      fullPath: '/audit/queries/'
      preLoaderRoute: typeof AuditQueriesIndexRouteImport
      parentRoute: typeof AuditQueriesRouteRoute
    }
    '/audit/plans/': {
      id: '/audit/plans/'
      path: '/'
      fullPath: '/audit/plans/'
      preLoaderRoute: typeof AuditPlansIndexRouteImport
      parentRoute: typeof AuditPlansRouteRoute
    }
    '/audit/categories/': {
      id: '/audit/categories/'
      path: '/'
      fullPath: '/audit/categories/'
      preLoaderRoute: typeof AuditCategoriesIndexRouteImport
      parentRoute: typeof AuditCategoriesRouteRoute
    }
    '/audit/queries/$queryId': {
      id: '/audit/queries/$queryId'
      path: '/$queryId'
      fullPath: '/audit/queries/$queryId'
      preLoaderRoute: typeof AuditQueriesQueryIdRouteImport
      parentRoute: typeof AuditQueriesRouteRoute
    }
    '/audit/plans/$planId': {
      id: '/audit/plans/$planId'
      path: '/$planId'
      fullPath: '/audit/plans/$planId'
      preLoaderRoute: typeof AuditPlansPlanIdRouteImport
      parentRoute: typeof AuditPlansRouteRoute
    }
    '/audit/categories/$categoryId': {
      id: '/audit/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/audit/categories/$categoryId'
      preLoaderRoute: typeof AuditCategoriesCategoryIdRouteImport
      parentRoute: typeof AuditCategoriesRouteRoute
    }
  }
}

interface AuditCategoriesRouteRouteChildren {
  AuditCategoriesCategoryIdRoute: typeof AuditCategoriesCategoryIdRoute
  AuditCategoriesIndexRoute: typeof AuditCategoriesIndexRoute
}

const AuditCategoriesRouteRouteChildren: AuditCategoriesRouteRouteChildren = {
  AuditCategoriesCategoryIdRoute: AuditCategoriesCategoryIdRoute,
  AuditCategoriesIndexRoute: AuditCategoriesIndexRoute,
}

const AuditCategoriesRouteRouteWithChildren =
  AuditCategoriesRouteRoute._addFileChildren(AuditCategoriesRouteRouteChildren)

interface AuditPlansRouteRouteChildren {
  AuditPlansPlanIdRoute: typeof AuditPlansPlanIdRoute
  AuditPlansIndexRoute: typeof AuditPlansIndexRoute
}

const AuditPlansRouteRouteChildren: AuditPlansRouteRouteChildren = {
  AuditPlansPlanIdRoute: AuditPlansPlanIdRoute,
  AuditPlansIndexRoute: AuditPlansIndexRoute,
}

const AuditPlansRouteRouteWithChildren = AuditPlansRouteRoute._addFileChildren(
  AuditPlansRouteRouteChildren,
)

interface AuditQueriesRouteRouteChildren {
  AuditQueriesQueryIdRoute: typeof AuditQueriesQueryIdRoute
  AuditQueriesIndexRoute: typeof AuditQueriesIndexRoute
}

const AuditQueriesRouteRouteChildren: AuditQueriesRouteRouteChildren = {
  AuditQueriesQueryIdRoute: AuditQueriesQueryIdRoute,
  AuditQueriesIndexRoute: AuditQueriesIndexRoute,
}

const AuditQueriesRouteRouteWithChildren =
  AuditQueriesRouteRoute._addFileChildren(AuditQueriesRouteRouteChildren)

interface AuditRouteRouteChildren {
  AuditCategoriesRouteRoute: typeof AuditCategoriesRouteRouteWithChildren
  AuditPlansRouteRoute: typeof AuditPlansRouteRouteWithChildren
  AuditQueriesRouteRoute: typeof AuditQueriesRouteRouteWithChildren
}

const AuditRouteRouteChildren: AuditRouteRouteChildren = {
  AuditCategoriesRouteRoute: AuditCategoriesRouteRouteWithChildren,
  AuditPlansRouteRoute: AuditPlansRouteRouteWithChildren,
  AuditQueriesRouteRoute: AuditQueriesRouteRouteWithChildren,
}

const AuditRouteRouteWithChildren = AuditRouteRoute._addFileChildren(
  AuditRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRouteRoute: AuditRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
