/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueriesRouteRouteImport } from './routes/queries/route'
import { Route as PlansRouteRouteImport } from './routes/plans/route'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueriesIndexRouteImport } from './routes/queries/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as QueriesQueryIdRouteImport } from './routes/queries/$queryId'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'

const QueriesRouteRoute = QueriesRouteRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRouteRoute = PlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesIndexRoute = QueriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueriesRouteRoute,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansRouteRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const QueriesQueryIdRoute = QueriesQueryIdRouteImport.update({
  id: '/$queryId',
  path: '/$queryId',
  getParentRoute: () => QueriesRouteRoute,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRouteRoute,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/plans': typeof PlansRouteRouteWithChildren
  '/queries': typeof QueriesRouteRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/queries/': typeof QueriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/queries': typeof QueriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/plans': typeof PlansRouteRouteWithChildren
  '/queries': typeof QueriesRouteRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/queries/$queryId': typeof QueriesQueryIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/queries/': typeof QueriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/plans'
    | '/queries'
    | '/categories/$categoryId'
    | '/plans/$planId'
    | '/queries/$queryId'
    | '/categories/'
    | '/plans/'
    | '/queries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories/$categoryId'
    | '/plans/$planId'
    | '/queries/$queryId'
    | '/categories'
    | '/plans'
    | '/queries'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/plans'
    | '/queries'
    | '/categories/$categoryId'
    | '/plans/$planId'
    | '/queries/$queryId'
    | '/categories/'
    | '/plans/'
    | '/queries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
  PlansRouteRoute: typeof PlansRouteRouteWithChildren
  QueriesRouteRoute: typeof QueriesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/': {
      id: '/queries/'
      path: '/'
      fullPath: '/queries/'
      preLoaderRoute: typeof QueriesIndexRouteImport
      parentRoute: typeof QueriesRouteRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof PlansRouteRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/queries/$queryId': {
      id: '/queries/$queryId'
      path: '/$queryId'
      fullPath: '/queries/$queryId'
      preLoaderRoute: typeof QueriesQueryIdRouteImport
      parentRoute: typeof QueriesRouteRoute
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRouteRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
  }
}

interface CategoriesRouteRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

interface PlansRouteRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

const PlansRouteRouteChildren: PlansRouteRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
  PlansIndexRoute: PlansIndexRoute,
}

const PlansRouteRouteWithChildren = PlansRouteRoute._addFileChildren(
  PlansRouteRouteChildren,
)

interface QueriesRouteRouteChildren {
  QueriesQueryIdRoute: typeof QueriesQueryIdRoute
  QueriesIndexRoute: typeof QueriesIndexRoute
}

const QueriesRouteRouteChildren: QueriesRouteRouteChildren = {
  QueriesQueryIdRoute: QueriesQueryIdRoute,
  QueriesIndexRoute: QueriesIndexRoute,
}

const QueriesRouteRouteWithChildren = QueriesRouteRoute._addFileChildren(
  QueriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
  PlansRouteRoute: PlansRouteRouteWithChildren,
  QueriesRouteRoute: QueriesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
